[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'xolox/vim-session'
hook_add = '''
  let g:session_autosave = 'yes'
  let g:session_autoload = 'yes'
'''

[[plugins]]
repo = 'xolox/vim-misc'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
  map <Leader>f <Plug>(easymotion-bd-f)
  nmap <Leader>f <Plug>(easymotion-overwin-f)

  map <Leader>/ <Plug>(easymotion-sn)
  omap <Leader>/ <Plug>(easymotion-tn)

  map <Leader>h <Plug>(easymotion-linebackward)
  map <Leader>l <Plug>(easymotion-lineforward)

  map <Leader>j <Plug>(easymotion-j)
  map <Leader>k <Plug>(easymotion-k)

  let g:EasyMotion_smartcase = 1
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
    set laststatus=2
    let g:airline_theme = 'deus'
    let g:airline_powerline_fonts = 1
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#buffer_idx_mode = 1
    let g:airline#extensions#virtualenv#enabled = 1
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'


[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'mattn/vim-goimports'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
    let g:hybrid_custom_term_colors = 1
    let g:hybrid_reduced_contrast = 1
'''

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'alvan/vim-closetag'

[[plugins]]
repo = 'junegunn/fzf'
hook_post_update = './install --all'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'Shougo/ddc.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  set updatetime=250
'''
